package com.fsales.app.rumo.ui.theme

import androidx.compose.ui.graphics.Color

// =============================================================================
// Paleta gerada via Material Theme Builder — seed: Azul-Índigo (#3949AB)
// https://m3.material.io/theme-builder
// =============================================================================

// --- Light scheme ---
val md_theme_light_primary                = Color(0xFF3651BA)
val md_theme_light_onPrimary              = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer       = Color(0xFFDDE1FF)
val md_theme_light_onPrimaryContainer     = Color(0xFF001159)
val md_theme_light_secondary              = Color(0xFF5B5D72)
val md_theme_light_onSecondary            = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer     = Color(0xFFE0E0F9)
val md_theme_light_onSecondaryContainer   = Color(0xFF181A2C)
val md_theme_light_tertiary               = Color(0xFF76536B)
val md_theme_light_onTertiary             = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer      = Color(0xFFFFD7F1)
val md_theme_light_onTertiaryContainer    = Color(0xFF2D1127)
val md_theme_light_error                  = Color(0xFFBA1A1A)
val md_theme_light_onError                = Color(0xFFFFFFFF)
val md_theme_light_errorContainer         = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer       = Color(0xFF410002)
val md_theme_light_background             = Color(0xFFFBF8FF)
val md_theme_light_onBackground           = Color(0xFF1B1B21)
val md_theme_light_surface               = Color(0xFFFBF8FF)
val md_theme_light_onSurface              = Color(0xFF1B1B21)
val md_theme_light_surfaceVariant         = Color(0xFFE3E1EC)
val md_theme_light_onSurfaceVariant       = Color(0xFF46464F)
val md_theme_light_outline                = Color(0xFF777680)
val md_theme_light_outlineVariant         = Color(0xFFC7C5D0)
val md_theme_light_scrim                  = Color(0xFF000000)
val md_theme_light_inverseSurface         = Color(0xFF303036)
val md_theme_light_inverseOnSurface       = Color(0xFFF2EFF7)
val md_theme_light_inversePrimary         = Color(0xFFB8C3FF)
val md_theme_light_surfaceTint            = Color(0xFF3651BA)

// --- Dark scheme ---
val md_theme_dark_primary                 = Color(0xFFB8C3FF)
val md_theme_dark_onPrimary               = Color(0xFF00218A)
val md_theme_dark_primaryContainer        = Color(0xFF1939A1)
val md_theme_dark_onPrimaryContainer      = Color(0xFFDDE1FF)
val md_theme_dark_secondary               = Color(0xFFC3C4DD)
val md_theme_dark_onSecondary             = Color(0xFF2D2F42)
val md_theme_dark_secondaryContainer      = Color(0xFF434559)
val md_theme_dark_onSecondaryContainer    = Color(0xFFE0E0F9)
val md_theme_dark_tertiary                = Color(0xFFE5BAD8)
val md_theme_dark_onTertiary              = Color(0xFF44263D)
val md_theme_dark_tertiaryContainer       = Color(0xFF5D3C54)
val md_theme_dark_onTertiaryContainer     = Color(0xFFFFD7F1)
val md_theme_dark_error                   = Color(0xFFFFB4AB)
val md_theme_dark_onError                 = Color(0xFF690005)
val md_theme_dark_errorContainer          = Color(0xFF93000A)
val md_theme_dark_onErrorContainer        = Color(0xFFFFDAD6)
val md_theme_dark_background              = Color(0xFF131318)
val md_theme_dark_onBackground            = Color(0xFFE4E1E9)
val md_theme_dark_surface                 = Color(0xFF131318)
val md_theme_dark_onSurface               = Color(0xFFE4E1E9)
val md_theme_dark_surfaceVariant          = Color(0xFF46464F)
val md_theme_dark_onSurfaceVariant        = Color(0xFFC7C5D0)
val md_theme_dark_outline                 = Color(0xFF918F9A)
val md_theme_dark_outlineVariant          = Color(0xFF46464F)
val md_theme_dark_scrim                   = Color(0xFF000000)
val md_theme_dark_inverseSurface          = Color(0xFFE4E1E9)
val md_theme_dark_inverseOnSurface        = Color(0xFF303036)
val md_theme_dark_inversePrimary          = Color(0xFF3651BA)
val md_theme_dark_surfaceTint             = Color(0xFFB8C3FF)

